### ISSUE TITLE
Bump SDK version

### ISSUE THREAD

**Issue by dpasqualin** [apptreesoftware/flutter_calendar#19]
Hi, I'm using the master channel on flutter (SDK 2.1), and when I run `flutter packages get` I receive the following error:

```
Because flutter_calendar 0.0.4 depends on date_utils any which requires SDK version >=1.20.1 <2.0.0, flutter_calendar 0.0.4 is forbidden. 
```
I've forked your projects (date_utils and flutter_calendar), changed the sdk requirement from `<2.0.0` to `<3.0.0` and apparently it still works good. I'm just not sure if I've made all necessary tests, do perhaps you could run the tests and update the package?

Thanks.

**Comment by ericwindmill** [comment]
This is fixed.
