### ISSUE TITLE
Crash when cancel on selecting a date

### ISSUE THREAD

**Issue by Paul-Todd** [apptreesoftware/flutter_calendar#2]
When you click on the calendar button it shows the calendar picker as it should but then if you click cancel the app crashes

"The getter year was called with null"

This is due to lines 314 & 315 referring to a date that is null in flutter_calendar.dart. Moving these inside the if statement will fix the issue

Do you need a PR or can you make the change?

Paul

**Comment by ericwindmill** [comment]
Fixed.
