### ISSUE TITLE
flutter calendar is not working properly in month mode as skips some months or repeat the successive one

### ISSUE THREAD

**Issue by isoos** [apptreesoftware/flutter_calendar#21]
_From @debutdeveloper on August 23, 2018 9:23_

URL: https://pub.dartlang.org/packages/flutter_calendar

This plugin is good for showing calendar in our apps but there are some issues occurred in expanded mode as it is working properly in week mode/ collapsed. 
In expanded mode, some months are skipped by this calendar and repeat the very next month.
So this is not very much stable.

Please provide us some solution!!

_Copied from original issue: dart-lang/pub-dartlang-dart#1549_

**Comment by Sadoge** [comment]
#24 Solution should be in here

**Comment by ericwindmill** [comment]
This is fixed thanks to @Sadoge  and others.
