### ISSUE TITLE
flutter_calendar >=0.0.3 depends on date_utils <0.1.0

### ISSUE THREAD

**Issue by IshanFx** [apptreesoftware/flutter_calendar#22]
How to fix this issue.

flutter_calendar >=0.0.3 depends on date_utils <0.1.0 which requires SDK version >=1.20.1 <2.0.0, flutter_calendar >=0.0.3 is forbidden.
So, because flutter_calendar <0.0.3 requires SDK version >=1.8.0 <2.0.0 and word_memorize depends on flutter_calendar any, version solving failed.
pub finished with exit code 1

**Comment by ntsdev** [comment]
Use like this pubspec.yaml the error will be gone then you can use the library

 flutter_calendar:
    git: https://github.com/apptreesoftware/flutter_calendar.git

**Comment by ericwindmill** [comment]
pub issues are fixed. Thanks all
