### ISSUE TITLE
Display month is not updated correctly

### ISSUE THREAD

**Issue by Sadoge** [apptreesoftware/flutter_calendar#24]
Going to the next or previous month is not updated correctly when the first day of the week is still in the previous month.

`
void nextMonth() {
    setState(() {
      today = Utils.nextMonth(today);
      final firstDateOfNewMonth = Utils.firstDayOfMonth(today);
      final lastDateOfNewMonth = Utils.lastDayOfMonth(today);
      updateSelectedRange(firstDateOfNewMonth, lastDateOfNewMonth);
      selectedMonthsDays = Utils.daysInMonth(today);
      displayMonth = Utils.formatMonth(Utils.firstDayOfWeek(today));
    });
  }
`

It is an easy fix, instead of getting the first day of the week, you just get the month of the current day. This should be in the correct month already.

`
void nextMonth() {
    setState(() {
      today = Utils.nextMonth(today);
      final firstDateOfNewMonth = Utils.firstDayOfMonth(today);
      final lastDateOfNewMonth = Utils.lastDayOfMonth(today);
      updateSelectedRange(firstDateOfNewMonth, lastDateOfNewMonth);
      selectedMonthsDays = Utils.daysInMonth(today);
      displayMonth = Utils.formatMonth(today);
    });
  }
`

**Comment by Sadoge** [comment]
This should be fixed in this pull request #18

**Comment by ericwindmill** [comment]
This is fixed. Tahnks again @Sadoge
