### ISSUE TITLE
It looks like you didn't push the version 0.0.4 available on pub.dartlang.or

### ISSUE THREAD

**Issue by zoechi** [apptreesoftware/flutter_calendar#26]
![image](https://user-images.githubusercontent.com/405837/45584413-2dc07d00-b8d3-11e8-931e-c3661e70d151.png)

![image](https://user-images.githubusercontent.com/405837/45584415-3913a880-b8d3-11e8-80a0-602b4868c6f1.png)

**Comment by johnpryan** [comment]
fyi @ericwindmill

**Comment by zoechi** [comment]
See also https://github.com/flutter/flutter/issues/21421#issuecomment-421540152
