### ISSUE TITLE
Example Flutter App has Errors

### ISSUE THREAD

**Issue by stephensamonte** [apptreesoftware/flutter_calendar#36]
I am not able to run the example application because it has errors.  Is this an issue that others have?

**Comment by WeellingtonCesa** [comment]
What's the error? Because here run nomally.

**Comment by santiagosantucho** [comment]
In a device (iPhone 6S) the example has an error: A RenderFlex overflowed by 3.0 pixels on the right. In the simulator for iPhone 6S works ok.

![img_0315](https://user-images.githubusercontent.com/1265913/49825104-605b0400-fd62-11e8-9198-68c702119f38.jpg)

**Comment by stephensamonte** [comment]
I had a different problem earlier. Revisiting the example program I ran into a different problem that I was able to solve. 

My new Problem was: 
`No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android`

<img width="960" alt="error" src="https://user-images.githubusercontent.com/30998408/50022944-c8e8f180-ffab-11e8-8457-91c6e788c66b.PNG">

This was because caused because I upgraded Android Studio. 

The solution can be found here: https://github.com/flutter/flutter/issues/22031#issuecomment-433662731

Open android/gradle/gradle-wrapper.properties and change this line:
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip`
to this line:
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

Open android/build.gradle and change this line:
`classpath 'com.android.tools.build:gradle:3.0.1'`
to this:
`classpath 'com.android.tools.build:gradle:3.1.2'`

I am now able to run the example program! Thank you for the assistance @WeellingtonCesa

**Comment by stephensamonte** [comment]
@santiagosantucho Overflow is a different issue than not being able to run the example application. So, I created a new issue for it.

> In a device (iPhone 6S) the example has an error: A RenderFlex overflowed by 3.0 pixels on the right. In the simulator for iPhone 6S works ok.
> 
> ![img_0315](https://user-images.githubusercontent.com/1265913/49825104-605b0400-fd62-11e8-9198-68c702119f38.jpg)
