### ISSUE TITLE
Larger screens

### ISSUE THREAD

**Issue by gedw99** [apptreesoftware/flutter_calendar#5]
For tablets the ability to show a bigger cal would be good.

Also different views:
- month
- week
- day
- schule which just shows them ordered.

**Comment by gedw99** [comment]
Any news on this ? I guess you don't need it and want a PR ?

I basically want to make something similar to the look of Google Calendar on your mobile.

**Comment by ericwindmill** [comment]
Sorry for taking so long to get back to you. We have no plans at the moment to add this functionality.
