### ISSUE TITLE
Flutter_calendar  Not compatible with intl 0.16.0 plz update

### ISSUE THREAD

**Issue by UnluckyY1** [apptreesoftware/flutter_calendar#59]
So, because siyou depends on both easy_localization ^1.3.1 and flutter calendar ^0.0.8, version solving failed
Because every version of easy localization depends on flutter_localizations any from sdk which depends on intl 0.16.0, every version of easy localization requires intl 0.16.0. So, because siyou depends on both intl ^0.15.8 and easy_localization ^1.3.1, version solving failed.

**Comment by xingx001** [comment]
it is   a long time  since  you   published last time  on Oct 16, 2018. 
now the Flutter   released   Ver 1.12.13

could you update the  intl  0.16.0？
